M48
; DRILL file {KiCad 6.0.4+dfsg-1+b1} date Fri 22 Apr 2022 12:30:20 PM CDT
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-04-22T12:30:20-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.4+dfsg-1+b1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0750
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X2.5Y-4.025
T2
X2.0Y-2.0
X2.0Y-4.0
X5.0Y-2.0
X5.0Y-4.0
T0
M30
